project:
  type: website
  output-dir: docs

website:
  title: "Homework 2"
  navbar:
    left:
      - href: Homework2_Combined.qmd
        text: "Homework 2 Submission"
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual