project:
  type: website
  output-dir: docs

website:
  title: "Homework 2"
  navbar:
    left:
      - href: Homework 2 Submission
        text: Home Work 2 Submission
      - Homework2_Combined.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
