project:
  type: website
  output-dir: docs

website:
  title: "Homework3"
  navbar:
    left:
      - href: Homework_3_Combined.qmd
        text: Homework 3 Combined

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
