---
title: "HW4"
---

\
Task 1

```{r}

iris |>
  as_tibble() |>
  select(starts_with("Petal"), Species) |>
  filter(Petal.Length < 1.55) |>
  arrange(Species)
```

wide format data has one row per subject, each variable stored in its own column. long format has one row per observation. Long format is preferred because most modern formats expect the data to be in a long format, computationally it is also faster, accessing data in the wide format causes the computer to have to jump ahead to access the next data point.

Task 2.\

```{r}



glass_data = read_csv(
  "https://www4.stat.ncsu.edu/~online/datasets/glass.data",
  col_names = c(
    "id", "refractive_index", "sodium", "magnesium", "aluminum",
    "silicon", "potassium", "calcium", "barium", "iron", "glass_type"
  ),
  show_col_types = FALSE
)
glass_data


glass_data = glass_data %>% mutate(glass_type = factor(glass_type, levels = 1:7,  labels =c("building_windows_float_processed",                           "building_windows_non_float_processed",                               "vehicle_windows_float_processed",                                               "vehicle_windows_non_float_processed",
"containers",                                                                 "tableware",
"headlamps"))) %>%
  filter(iron < 0.2,
         glass_type %in% c("tableware", "headlamps"))
```

```{r}
yeast_data = read_table(
  "https://www4.stat.ncsu.edu/~online/datasets/yeast.data",
  col_names = c(
    "seq_name", "mcg", "gvh", "alm", "mit",
    "erl", "pox", "vac", "nuc", "class"
  ),
  show_col_types = FALSE
)

yeast_data

yeast_data=yeast_data %>% select(-seq_name,-nuc)%>%group_by(class)%>%mutate(across(c(mcg,gvh,alm,mit,erl,pox,vac),list(mean=mean,median=median),.names="{.col}_{.fn}"))
yeast_data
```

```{r}

white_wine = read_excel("white-wine.xlsx", sheet = 1)
white_wine


name_key = read_excel("white-wine.xlsx", sheet = 2)


colnames(white_wine) = name_key[[1]]

white_wine$type = "white"

white_wine



red_wine = read_delim(
  "https://www4.stat.ncsu.edu/~online/datasets/red-wine.csv",
  delim = ";",
  show_col_types = FALSE)


colnames(red_wine) = name_key[[1]]
red_wine$type = "red"

red_wine


wine_data = dplyr::bind_rows(white_wine, red_wine)
wine_data

wine_data=wine_data%>%filter(quality>6.5)%>%filter(alcohol<132)%>%arrange(desc(alcohol))%>%select(contains("acid"),quality,alcohol,type)%>%mutate(alcohol_mean=mean(alcohol),alcohol_sd=sd(alcohol))%>%ungroup()
wine_data
```
